name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build plugin
        run: |
          pnpm install
          pnpm run build

      - name: Build sandbox
        run: |
          cd sandbox
          pnpm install
          pnpm run build
